BallGame1
Nikita-Mohov/BallGame pull request #1
Opened 2019-10-11 16:44 UTC by Nikita-Mohov

Понимаю, что сделал не самый лучший спавн монет, но не знаю, как сделать по-другому. Хотелось бы услышать твои советы по этому поводу.

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/CoinCounter.cs
> +    private static Text _counterText;
static лишнее

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/CoinCounter.cs
> +        _counterText = GetComponent<Text>();
Используй назначение через инспектор 
Поля делай [SerializeField] private которые планируется назначать в инспекторе

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/CoinCounter.cs
> +    }
static не нужен

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/CoinCounter.cs
> +    public static void WriteValue()
Этот метод лучше сделать private

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/MainMenu.cs
> +    public Animator Authors;
[SerializeField] private

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/MainMenu.cs
> +        Authors.SetBool("IsOpen", !state);
ShowAuthors показывает а не инвертирует

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/PauseMenu.cs
> +
Лишняя строка

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/PauseMenu.cs
> +            if (_gameIsPaused == true)
Тут достаточно только
if (_gameIsPaused)

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/PauseMenu.cs
> +    protected bool _gameIsPaused = false;
private

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/PauseMenu.cs
> +    [SerializeField] private GameObject _pauseMenu;
Старайся делать [SerializeField] выше остальных полей

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/InterfaseScripts/PauseMenu.cs
> +        Time.timeScale = 1f;
_gameIsPaused менять не нужно тут?

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/Coin.cs
> +            CoinCounter.AddCoin();
Когда уберёшь статик подумай как сюда передать счётчик монеток

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/OncomingObjects.cs
> +
Лишняя строка

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/OncomingObjects.cs
> +    private void Start()
Между полями и методом нужна пустая строка

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/OncomingObjects.cs
> +    [SerializeField] protected float _destroyTime;
private вместо protected

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/OncomingObjects.cs
> +﻿using System.Collections;
Название папки сделай просто OncomingObjects

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/Spawner.cs
> +    [SerializeField] private GameObject _coin;
_coinTemplate

2019-10-14 21:34 UTC, HolyMonkey commented on Assets/Scripts/OncominObjectsScripts/Spawner.cs
> +    private IEnumerator Spawn()
Раздели код. Отдельно сделай спавн монеток и отдельно спавн барьеров

2019-10-19 19:58 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +    private  Text _counterText;
_coinsText

2019-10-19 19:58 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +        _counterText = GetComponent<Text>();
Сделай назначение через инспектор

2019-10-19 19:58 UTC, HolyMonkey commented on Assets/Scripts/Interfase/MainMenu.cs
> +    public void InvertAuthorsOpenness()
ToggleAuthors

2019-10-19 19:58 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/Spawner.cs
> +public class Spawner : MonoBehaviour
Спавнеры всё ещё не разделены

2019-10-23 20:10 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/BarrierSpawner.cs
> +            _timeToSpawn -= Time.deltaTime;
Здесь тоже нужным скобки

2019-10-23 20:10 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/BarrierSpawner.cs
> +            _IsSpawned = true;
Логика из-за этого флага запутана. Упрости её, это тут возможно

2019-10-23 20:10 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawner.cs
> +    private bool _IsSpawned;
А теперь все похожие части выдели в общий базовый класс

2019-10-23 20:10 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawner.cs
> +            Instantiate(_coinTemplate, _pointsOfCoinSpawn[coinspawnpoint].transform.position, _pointsOfCoinSpawn[coinspawnpoint].transform.rotation);
Запутанная логика

2019-10-24 14:41 UTC, moknick commented on Assets/Scripts/OncominObjects/CoinSpawner.cs
> +            Instantiate(_coinTemplate, _pointsOfCoinSpawn[coinspawnpoint].transform.position, _pointsOfCoinSpawn[coinspawnpoint].transform.rotation);
Не понимаю, что именно запутано. Образование дуг, тайминги или спавн в общем?

2019-11-04 17:28 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +    [SerializeField] private  Text _counterText;
Поля с [SerializeField]  размещаются выше и отделяются от остальных пустой строкой

2019-11-04 17:28 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +        _counterText.text = "Coins: " + _value;
Код дублируется с 24-ой строкой

2019-11-04 17:28 UTC, HolyMonkey commented on Assets/Scripts/Interfase/PauseMenu.cs
> +    }
В DeathMenu аналогичный метод

2019-11-04 17:28 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/Barrier.cs
> +        }
Давай перенесём это в PlayerDeath

2019-11-04 17:29 UTC, HolyMonkey commented
Спавнеры перепиши. Очень переусложнены

2020-02-12 11:39 UTC, HolyMonkey requested changes

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/Interfase/PauseMenu.cs
> +    private bool _gameIsPaused = false;
_isGamePaused

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +    [SerializeField] private Text _counterText;
_valueView

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/Interfase/PauseMenu.cs
> +    [SerializeField] private GameObject _pauseMenu;
Не совсем понятно почему это называется одинаково

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/Coin.cs
> +        if (_spawnPoint.transform.position.x - gameObject.transform.position.x >=  _coinSpawner.DistanceBetweenCoins  && !_isMovedAway)
Монетка движется пока не уйдёт за пределы дистанции между монетками? Не понимаю логику

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawnPoint.cs
> +    public void GetSpeed(float speed)
Почему Get?

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawnPoint.cs
> +    [SerializeField] private Transform[] _movingPoints;
_arcPath?

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawnPoint.cs
> +                    _currentPoint = 0;
Это точно должно быть интом? Это описывает состояние либо 0 либо 1? Не понятно что значит 1 а что 0

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawnPoint.cs
> +                    _currentPoint = 0;
Попробуй использовать перечисления

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawner.cs
> +    [SerializeField] private GameObject[] _pointsOfCoinSpawn;
Непонятно что это

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/CoinSpawner.cs
> +    [SerializeField] private float _rowLength;
Отсортируй поля, выше приватные с аттрибутом SerializeField потом приватные

2020-02-12 11:39 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/ObjectsSpawner.cs
> +public class ObjectsSpawner : MonoBehaviour
CoinSpawner  и этот класс дублируются друг друга

2020-03-16 20:42 UTC, HolyMonkey requested changes

2020-03-16 20:42 UTC, HolyMonkey commented on Assets/Scripts/Interfase/CoinCounter.cs
> +    private int _valueView = 0;
Ты не то назвал _valueView

2020-03-16 20:42 UTC, HolyMonkey commented on Assets/Scripts/Interfase/MainMenu.cs
> +    [SerializeField] private Animator Authors;
Мы не так называем приватные поля

2020-03-16 20:42 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelPart.cs
> +    public float Speed
Speed => _speed

2020-03-16 20:42 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelPart.cs
> +    public event UnityAction OnArrival;
https://trello.com/c/CsOZfMhi/1-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2

2020-03-16 20:42 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelPart.cs
> +        _player = GameObject.FindObjectOfType<Player>();
Мы не используем FindObjectOfType

2020-03-26 12:05 UTC, HolyMonkey requested changes

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/Interfase/PauseGame.cs
> +}
Дубляж кода

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/Interfase/PauseGame.cs
> +    public void Resume()
Почему паблик?

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/Coin.cs
> +        if(playerCoinPick != null)
Попробуй тут TryGetComponent

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelPart.cs
> +        Invoke("Destroy", _destroyTime);
Мы не используем Invoke

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelSpawner.cs
> +
Здесь пустая строка лишняя

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelSpawner.cs
> +        LevelPart spawnedLevelPart = Instantiate(_levelParts[Random.Range(0, _levelParts.Length)], _spawnPoint.position, Quaternion.identity);
_levelParts[Random.Range(0, _levelParts.Length)] вынеси в метод

2020-03-26 12:05 UTC, HolyMonkey commented on Assets/Scripts/OncominObjects/LevelSpawner.cs
> +        foreach (LevelPart lp in GameObject.FindObjectsOfType<LevelPart>())
GameObject.FindObjectsOfType мы не используем

2020-04-01 09:39 UTC, merged